### ISSUE TITLE
Changing pitch mode still produces annoying popup warning of official build

### ISSUE THREAD

**Issue by Saikode** [jimbo1qaz/j0CC-FamiTracker#139]
Changing the pitch mode for the first time after launching any given instance of j0cc-FT will warn the user that linear pitch is a "planned feature in the official build." Although I suspect this was a real possibility when 0cc was first developed, it's clear by now that a new official build of vanilla FT isn't something we have to worry about. (For that matter, Hertz never saw fit to warn users of any other features that would cause back-compat with vanilla FT to break...)
Being someone who uses linear pitch in nearly every module I create, and being fairly certain there are others with similar habits, it would save a lot of users a lot of clicks in short order if this popup was removed.

**Comment by jimbo1qaz** [comment]
Fixed in #144 quite a while back, but I haven't made a release since then. You can download from https://ci.appveyor.com/api/buildjobs/slh1s3i4wcju5e75/artifacts/Release%2Fj0CC-Dev-157.exe .
