### ISSUE TITLE
New feature for j0cc-famitacker

### ISSUE THREAD

**Issue by babatunde3** [jimbo1qaz/j0CC-FamiTracker#157]
Can you add sunsoft 5b please? Thanks

**Comment by jimbo1qaz** [comment]
yeah, j0cc and 0cc already support 5B.

**Comment by babatunde3** [comment]
But sunsoft 5b isn't there in the detune settings

**Comment by jimbo1qaz** [comment]
I am aware that the detune dialog is confusing, for me too. I didn't design it. I just tested the dialog, and 5B detune is controlled using the 2A03 options.
